--- #YAML:1.0
name:               Text-Metaphone
version:            2.01
abstract:           A modern soundex.  Phonetic encoding of words.
author:
    - Michael G Schwern <schwern@pobox.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:        5.6.0
    Test::More:  0.47
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Text-Metaphone
    homepage:    http://search.cpan.org/dist/Text-Metaphone/
    license:     http://dev.perl.org/licenses/
    repository:  http://svn.schwern.org/repos/CPAN/Text-Metaphone
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
